export type Gender = "male" | "female" | "neutral";

const commonMaleNames = new Set([
  "aaron",
  "adam",
  "adrian",
  "alan",
  "albert",
  "alex",
  "alexander",
  "andrew",
  "anthony",
  "antonio",
  "arthur",
  "benjamin",
  "bob",
  "bobby",
  "brandon",
  "brian",
  "bruce",
  "carlos",
  "charles",
  "chris",
  "christopher",
  "daniel",
  "david",
  "dennis",
  "donald",
  "douglas",
  "edward",
  "eric",
  "frank",
  "gary",
  "george",
  "harold",
  "harry",
  "henry",
  "jack",
  "james",
  "jason",
  "jeffrey",
  "jerry",
  "john",
  "jonathan",
  "joseph",
  "joshua",
  "juan",
  "kenneth",
  "kevin",
  "larry",
  "lawrence",
  "mark",
  "matthew",
  "michael",
  "nicholas",
  "noah",
  "patrick",
  "paul",
  "peter",
  "philip",
  "raymond",
  "richard",
  "robert",
  "ronald",
  "ryan",
  "samuel",
  "scott",
  "sean",
  "stephen",
  "steven",
  "thomas",
  "timothy",
  "todd",
  "walter",
  "wayne",
  "william",
  "zachary",
]);

const commonFemaleNames = new Set([
  "amanda",
  "amy",
  "andrea",
  "angela",
  "anna",
  "ashley",
  "barbara",
  "betty",
  "brenda",
  "carol",
  "carolyn",
  "catherine",
  "cheryl",
  "christina",
  "christine",
  "cynthia",
  "deborah",
  "debra",
  "denise",
  "diane",
  "donna",
  "dorothy",
  "elizabeth",
  "emily",
  "emma",
  "evelyn",
  "frances",
  "helen",
  "janet",
  "janice",
  "jean",
  "jennifer",
  "jessica",
  "joan",
  "joyce",
  "judith",
  "judy",
  "julia",
  "julie",
  "karen",
  "kathleen",
  "kathryn",
  "kelly",
  "kimberly",
  "laura",
  "linda",
  "lisa",
  "lori",
  "margaret",
  "maria",
  "marie",
  "marilyn",
  "martha",
  "mary",
  "michelle",
  "nancy",
  "nicole",
  "olivia",
  "pamela",
  "patricia",
  "rachel",
  "rebecca",
  "ruth",
  "sandra",
  "sara",
  "sarah",
  "sharon",
  "shirley",
  "stephanie",
  "susan",
  "teresa",
  "theresa",
  "virginia",
]);

const maleEndings = ["son", "ton", "man", "rick", "ard"];
const femaleEndings = ["a", "ia", "ine", "elle", "ette", "lyn", "leigh", "ko"];

export function inferGenderFromName(name: string): Gender | null {
  const lowerName = name.toLowerCase().trim();
  if (commonMaleNames.has(lowerName)) return "male";
  if (commonFemaleNames.has(lowerName)) return "female";
  for (const ending of maleEndings) {
    if (lowerName.endsWith(ending)) return "male";
  }
  for (const ending of femaleEndings) {
    if (lowerName.endsWith(ending)) return "female";
  }
  return null;
}
